config/routes.rb
Rails.application.routes.draw do
  devise_for :user

  match '/v0/*path', to: 'api#cors_preflight', via: [:options]
  match '/v1/*path', to: 'api#cors_preflight', via: [:options]
  get 'status' => 'status#status'

  get 'auth/login', to: 'auth#new', as: 'saml_login'
  post 'saml/auth/callback', to: 'auth#callback', as: 'saml_callback'
  get 'saml/metadata', to: 'auth#metadata'

  root 'application#home'

  # For active? helper
  get '/dashboards' => 'dashboards#index'
  post '/dashboards/build' => 'dashboards#build', as: :dashboard_build
  get '/dashboards/export/:csv_type' => 'dashboards#export', as: :dashboard_export, defaults: { format: 'csv' }
  get '/dashboards/api_fetch/:csv_type' => 'dashboards#api_fetch', as: :dashboard_api_fetch
  get '/dashboards/export/institutions/:number' => 'dashboards#export_version', as: :dashboard_export_version, defaults: { format: 'csv' }
  post '/dashboards/push' => 'dashboards#push', as: :dashboard_push

  resources :uploads, except: [:new, :destroy, :edit, :update] do
    get '(:csv_type)' => 'uploads#new', on: :new, as: ''
  end

  get '/groups', to: redirect('/uploads')
  resources :groups, except: [:new, :destroy, :edit, :update] do
    get '(:group_type)' => 'groups#new', on: :new, as: ''
  end

  get '/crosswalk_issues/partials' => 'crosswalk_issues#partials', as: :crosswalk_issues_partials
  get '/crosswalk_issues/partials/:id' => 'crosswalk_issues#show_partial', as: :crosswalk_issues_partials_show
  post '/crosswalk_issues/partials' => 'crosswalk_issues#resolve_partial', as: :crosswalk_issues_resolve_partial

  get '/crosswalk_issues/orphans' => 'crosswalk_issues#orphans', as: :crosswalk_issues_orphans

  get '/archives' => 'archives#index'
  get '/archives/export/:csv_type/:number' => 'archives#export', as: :archives_export, defaults: { format: 'csv' }
  get '/calculator_constants' => 'calculator_constants#index'
  post '/calculator_constants' => 'calculator_constants#update', as: :calculator_constants_update

  resources :storages, only: [:index, :edit, :update, :show] do
    get 'download' => 'storages#download', on: :member, defaults: { format: 'csv' }
  end

  namespace :v0, defaults: { format: 'json' } do
    get '/calculator/constants' => 'calculator_constants#index'

    resources :institutions, only: [:index, :show] do
      get :autocomplete, on: :collection
      get :children, on: :member
    end

    resources :institution_programs, only: [:index] do
      get :autocomplete, on: :collection
    end

    resources :yellow_ribbon_programs, only: :index

    resources :zipcode_rates, only: :show
  end

  namespace :v1, defaults: { format: 'json' } do
    get '/calculator/constants' => 'calculator_constants#index'

    resources :institutions, only: [:index, :show] do
      get :autocomplete, on: :collection
      get :children, on: :member
    end

    resources :institution_programs, only: [:index] do
      get :autocomplete, on: :collection
    end

    resources :yellow_ribbon_programs, only: :index

    resources :zipcode_rates, only: :show
  end
end

app/models/crosswalk_issue.rb
# frozen_string_literal: true

class CrosswalkIssue < ApplicationRecord
  PARTIAL_MATCH_TYPE = 'PARTIAL_MATCH_TYPE'
  IPEDS_ORPHAN_TYPE = 'IPEDS_ORPHAN_TYPE'

  belongs_to :crosswalk
  belongs_to :ipeds_hd
  belongs_to :weam

  scope :by_issue_type, ->(n) { where(issue_type: n) }

  def resolved?
    weam_ipeds_hd_match? && weam_crosswalk_match?
  end

  # rubocop:disable Metrics/MethodLength
  def self.rebuild
    sql = <<-SQL
      INSERT INTO crosswalk_issues (
        weam_id,
        crosswalk_id,
        ipeds_hd_id,
        issue_type
      )
      SELECT
        weams.id,
        crosswalks.id,
        ipeds_hds.id,
        '#{PARTIAL_MATCH_TYPE}'
      FROM weams
        LEFT OUTER JOIN ipeds_hds ON  weams.cross = ipeds_hds.cross
          OR weams.ope = ipeds_hds.ope
        LEFT OUTER JOIN crosswalks ON weams.facility_code = crosswalks.facility_code
      WHERE
        (institution_of_higher_learning_indicator = true OR non_college_degree_indicator = true)
        AND LOWER(poo_status) = 'aprvd'
        AND LENGTH(applicable_law_code) > 0
        AND LOWER(applicable_law_code) != 'educational institution is not approved'
        AND LOWER(applicable_law_code) != 'educational institution is approved for chapter 31 only'
        AND NOT(
          weams.cross IS NOT NULL
          AND ipeds_hds.cross IS NOT NULL
          AND crosswalks.cross IS NOT NULL
          AND weams.cross = ipeds_hds.cross
          AND weams.cross = crosswalks.cross
        )
        AND NOT(
          weams.cross IS NULL
          AND weams.ope IS NULL
          AND ipeds_hds.ope IS NULL
          AND crosswalks.cross IS NULL
          AND crosswalks.ope IS NULL
        )
        AND UPPER(weams.campus_type) is distinct from 'E'
      UNION
      SELECT
        NULL,
        crosswalks.id,
        ipeds_hds.id,
        '#{IPEDS_ORPHAN_TYPE}'
      FROM ipeds_hds
        LEFT OUTER JOIN crosswalks ON ipeds_hds.cross = crosswalks.cross OR ipeds_hds.ope = crosswalks.ope
      WHERE crosswalks.ID IS NULL;

      DELETE
      FROM crosswalk_issues
      WHERE id IN(
        SELECT crosswalk_issues.id FROM crosswalk_issues
          INNER JOIN weams on weams.id = weam_id
          LEFT OUTER JOIN ipeds_hds ON ipeds_hds.id = ipeds_hd_id
          LEFT OUTER JOIN crosswalks ON crosswalks.id = crosswalk_id
          INNER JOIN ignored_crosswalk_issues
            ON weams.facility_code = ignored_crosswalk_issues.facility_code
            AND (
              (ipeds_hds.cross IS NOT DISTINCT FROM ignored_crosswalk_issues.cross
                AND ipeds_hds.ope IS NOT DISTINCT FROM ignored_crosswalk_issues.ope)
              OR (crosswalks.cross IS NOT DISTINCT FROM ignored_crosswalk_issues.cross
                AND crosswalks.ope IS NOT DISTINCT FROM ignored_crosswalk_issues.ope)
            )
      );
    SQL

    InstitutionProgram.connection.execute(sql)
  end
  # rubocop:enable Metrics/MethodLength

  private

  def weam_ipeds_hd_match?
    weam.present? && ipeds_hd.present? &&
      weam.cross == ipeds_hd.cross && weam.ope == ipeds_hd.ope
  end

  def weam_crosswalk_match?
    weam.present? && crosswalk.present? &&
      weam.cross == crosswalk.cross && weam.ope == crosswalk.ope
  end
end

app/controllers/crosswalk_issues_controller.rb
# frozen_string_literal: true

class CrosswalkIssuesController < ApplicationController
  def partials
    @issues = CrosswalkIssue.includes(:crosswalk, :ipeds_hd, weam: :arf_gi_bill)
                            .by_issue_type(CrosswalkIssue::PARTIAL_MATCH_TYPE)
                            .order('arf_gi_bills.gibill desc nulls last, weams.institution, weams.facility_code')
  end

  def show_partial
    @issue = CrosswalkIssue.by_issue_type(CrosswalkIssue::PARTIAL_MATCH_TYPE).find(params[:id])
    @possible_ipeds_matches = possible_ipeds_matches(@issue)
  end

  def resolve_partial
    @issue = CrosswalkIssue.by_issue_type(CrosswalkIssue::PARTIAL_MATCH_TYPE).find(params[:id])

    crosswalk = update_or_create_crosswalk(@issue)
    @issue.crosswalk = crosswalk

    ignore_issue(@issue) if params[:ignore]

    if @issue.resolved? || params[:ignore]
      @issue.delete
      flash.notice = 'Crosswalk issue resolved'
      redirect_to action: :partials
    else
      @issue.save
      flash.notice = 'Crosswalk record updated'
      redirect_to action: :show_partial, id: @issue.id
    end
  end

  def orphans
    @issues = CrosswalkIssue.includes(%i[weam crosswalk ipeds_hd])
                            .by_issue_type(CrosswalkIssue::IPEDS_ORPHAN_TYPE)
                            .order('ipeds_hds.institution')
  end

  private

  # rubocop:disable Metrics/MethodLength
  def possible_ipeds_matches(issue)
    address_data_to_match = ApplicationRecord.connection.quote(issue.weam.address_values_for_match.join)
    physical_address_data = ApplicationRecord.connection.quote(issue.weam.physical_address_values_for_match.join)
    institution = ApplicationRecord.connection.quote(issue.weam.institution)

    str = <<-SQL
        SELECT
          id,
          ipeds_hds.cross,
          institution,
          addr,
          state,
          city,
          zip,
          ope,
          (
            GREATEST(
              SIMILARITY(COALESCE(city,'')||COALESCE(zip,'')||COALESCE(addr,''), #{address_data_to_match}),
              SIMILARITY(COALESCE(city,'')||COALESCE(zip,'')||COALESCE(addr,''), #{physical_address_data})
            )
            + SIMILARITY(institution, #{institution})
          ) / 2 AS match_score
        FROM ipeds_hds
        WHERE
          (
            SIMILARITY(institution, #{institution}) > 0.5
            OR SIMILARITY(COALESCE(city,'')||COALESCE(zip,'')||COALESCE(addr,''), #{address_data_to_match}) > 0.3
            OR SIMILARITY(COALESCE(city,'')||COALESCE(zip,'')||COALESCE(addr,''), #{physical_address_data}) > 0.3
          )
          AND (state = '#{issue.weam.physical_state}' OR state = '#{issue.weam.state}')
        ORDER BY match_score DESC
    SQL
    ApplicationRecord.connection.execute(ApplicationRecord.sanitize_sql(str))
  end
  # rubocop:enable Metrics/MethodLength

  def update_or_create_crosswalk(issue)
    crosswalk = issue.crosswalk.presence || Crosswalk.new
    crosswalk.facility_code = issue.weam.facility_code
    crosswalk.institution = issue.weam.institution
    crosswalk.city = issue.weam.city
    crosswalk.state = issue.weam.state
    crosswalk.cross = params['cross']
    crosswalk.ope = params['ope']
    crosswalk.notes = params['notes']
    crosswalk.save

    crosswalk
  end

  def ignore_issue(issue)
    IgnoredCrosswalkIssue.create(
      cross: issue.ipeds_hd.present? ? issue.ipeds_hd.cross : issue.crosswalk.cross,
      ope: issue.ipeds_hd.present? ? issue.ipeds_hd.ope : issue.crosswalk.ope,
      facility_code: issue.weam.facility_code
    )
  end
end

app/views/crosswalk_issues/_orphan_issues.html.erb
<tr class="<%= cycle('even', 'odd') -%>">
  <td><%= issue.ipeds_hd.institution %></td>
  <td><%= issue.ipeds_hd.cross %></td>
  <td><%= issue.ipeds_hd.ope %></td>
</tr>

app/views/crosswalk_issues/_partial_issues.html.erb
<tr class="<%= cycle('even', 'odd') -%>">
  <td><%= issue.weam.arf_gi_bill&.gibill %></td>
  <td><%= issue.weam.institution %></td>
  <td><%= issue.weam.facility_code %></td>
  <td><%= issue.weam.cross %></td>
  <td><%= issue.weam.ope %></td>
  <td><%= issue.ipeds_hd&.cross %></td>
  <td><%= issue.ipeds_hd&.ope %></td>
  <td><%= issue.crosswalk&.cross %></td>
  <td><%= issue.crosswalk&.ope %></td>
  <td>
    <%= link_to 'Fix', crosswalk_issues_partials_show_path(issue), class: "btn dashboard-btn-success" %>
  </td>
</tr>

app/views/crosswalk_issues/orphans.html.erb
<div class="row row-space-6" style="padding-bottom: 10px">
  <div class="col-xs-12">
    <h3>Ipeds issues</h3>
    <table class="table table-hover table-condensed table-bordered table-responsive crosswalk-issues">
      <thead class="system-header">
        <th colspan="3">IPEDS HD</th>
      </thead>
      <thead class="sub">
        <th>Institution Name</th>
        <th>IPEDS</th>
        <th>OPE</th>
      </thead>
      <tbody>
      <%= render partial: 'orphan_issues', collection: @issues, as: :issue %>
      </tbody>
    </table>
  </div>
</div>

app/views/crosswalk_issues/partials.html.erb
<div class="row row-space-6" style="padding-bottom: 10px">
  <div class="col-xs-12">
    <h2>Issues</h2>
    <table class="table table-hover table-condensed table-bordered table-responsive crosswalk-issues">
      <thead class="system-header">
        <th colspan="1">ArfGiBill</th>
        <th colspan="4">WEAMS</th>
        <th colspan="2">IPEDS HD</th>
        <th colspan="3">Crosswalk</th>
      </thead>
      <thead class="sub">
        <th># GI Bill Students</th>
        <th>Institution Name</th>
        <th>Facility Code</th>
        <th>IPEDS</th>
        <th>OPE</th>
        <th>IPEDS</th>
        <th>OPE</th>
        <th>IPEDS</th>
        <th>OPE</th>
        <th>Action</th>
      </thead>
      <tbody>
      <%= render partial: 'partial_issues', collection: @issues, as: :issue %>
      </tbody>
    </table>
  </div>
</div>

app/views/crosswalk_issues/show.html.erb
<div class="row row-space-6" style="padding-bottom: 10px">
  <div class="col-xs-12 ">

    <div class="row row-space-12">
      <div class="col-xs-12">
        <h2>Weams</h2>
        <table class="table table-hover table-condensed table-bordered table-responsive">
          <thead>
            <th>Name</th>
            <th>Facility Code</th>
            <th>City</th>
            <th>State</th>
            <th>IPEDS</th>
            <th>OPE</th>
          </thead>
          <tbody>
            <td><%= @issue.weam.institution %></td>
            <td><%= @issue.weam.facility_code %></td>
            <td><%= @issue.weam.city %></td>
            <td><%= @issue.weam.state %></td>
            <td><%= @issue.weam.cross %></td>
            <td><%= @issue.weam.ope %></td>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row row-space-12">
      <div class="col-xs-12">
        <h2>IPEDS HD</h2>
        <table class="table table-hover table-condensed table-bordered table-responsive">
          <thead>
          <th>Name</th>
          <th>City</th>
          <th>State</th>
          <th>IPEDS</th>
          <th>OPE</th>
          </thead>
          <tbody>
          <td><%= @issue.ipeds_hd&.institution %></td>
          <td><%= @issue.ipeds_hd&.city %></td>
          <td><%= @issue.ipeds_hd&.state %></td>
          <td><%= @issue.ipeds_hd&.cross %></td>
          <td><%= @issue.ipeds_hd&.ope %></td>
          </tbody>
        </table>
      </div>
    </div>


    <div class="row row-space-12">
      <div class="col-xs-12">
        <h2>Crosswalk</h2>
      </div>
    </div>
    <div class="row row-space-12">
      <div class="col-xs-12">
        <%= form_with(url: "/crosswalk_issues/resolve", method: "post") do %>
          <input type="hidden" name="id" value="<%= @issue.id %>" />
          <table class="table table-hover table-condensed table-bordered table-responsive">
            <thead>
              <th>Name</th>
              <th>Facility Code</th>
              <th>City</th>
              <th>State</th>
              <th>IPEDS</th>
              <th>OPE</th>
              <th>NOTES</th>
            </thead>
            <tbody>
              <td>
                <% if @issue.crosswalk.present? && @issue.weam.institution != @issue.crosswalk.institution %>
                  <div class="weams_override"><del><%= @issue.crosswalk&.institution %></del></div>
                <% end %>
                <%= @issue.weam.institution %>
              </td>
              <td>
                <% if @issue.crosswalk.present? && @issue.weam.facility_code != @issue.crosswalk.facility_code %>
                  <div class="weams_override"><del><%= @issue.crosswalk&.facility_code %></del></div>
                <% end %>
                <%= @issue.weam.facility_code %>
              </td>
              <td>
                <% if @issue.crosswalk.present? && @issue.weam.city != @issue.crosswalk.city %>
                  <div class="weams_override"><del><%= @issue.crosswalk&.city %></del></div>
                <% end %>
                <%= @issue.weam.city %>
              </td>
              <td>
                <% if @issue.crosswalk.present? && @issue.weam.state != @issue.crosswalk.state %>
                  <div class="weams_override"><del><%= @issue.crosswalk&.state %></del></div>
                <% end %>
                <%= @issue.weam.state %>
              </td>
              <td>
                <%= text_field_tag(:cross, @issue.crosswalk&.cross) %>
              </td>
              <td>
                <%= text_field_tag(:ope, @issue.crosswalk&.ope) %>
              </td>
              <td>
                <%= text_field_tag(:notes, @issue.crosswalk&.notes) %>
              </td>
            </tbody>
          </table>

          <input
            type="button"
            id="set_from_ipeds"
            class="btn btn-info crosswalk_update"
            value="Update Crosswalk from WEAMS"
            cross="<%= @issue.weam.cross %>"
            ope="<%= @issue.weam.ope %>"
          />

          <input
            type="button"
            id="set_from_weams"
            class="btn btn-info crosswalk_update"
            <%= @issue.ipeds_hd.presence || 'disabled' %>
            value="Update Crosswalk from IPEDS"
            cross="<%= @issue.ipeds_hd&.cross %>"
            ope="<%= @issue.ipeds_hd&.ope %>"
          />

          <input type="button" id="clear_ipeds_ope" class="btn btn-info" value="Clear IPEDS/OPE" />

          <%= submit_tag("Update", class: 'btn btn-success') %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/crosswalk_issues/show_partial.html.erb
<div class="row row-space-6" style="padding-bottom: 10px">
  <div class="col-xs-12 ">

    <div class="row row-space-12">
      <div class="col-xs-12">
        <h2>Weams</h2>
        <table class="table table-hover table-condensed table-bordered table-responsive">
          <thead>
            <th>Name</th>
            <th>Facility Code</th>
            <th>Full Address</th>
            <th>Full Physical Address</th>
            <th>IPEDS</th>
            <th>OPE</th>
            <th>Action</th>
          </thead>
          <tbody>
            <tr>
              <td><%= @issue.weam.institution %></td>
              <td>
                <%= link_to @issue.weam.facility_code,
                            "#{Version.current_production.gibct_link}/profile/#{@issue.weam.facility_code}",
                            target: :_blank
                %>
              </td>
              <td><%= @issue.weam.address_values.join(", ") %></td>
              <td><%= @issue.weam.physical_address_values.join(", ") %></td>
              <td><%= @issue.weam.cross %></td>
              <td><%= @issue.weam.ope %></td>
              <td>
                <input
                  type="button"
                  class="btn dashboard-btn-success crosswalk_update"
                  value="Match"
                  cross="<%= @issue.weam.cross %>"
                  ope="<%= @issue.weam.ope %>"
                  />
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row row-space-12">
      <div class="col-xs-12">
        <h2>IPEDS HD</h2>
        <% if @possible_ipeds_matches.any? %>
          <table class="table table-hover table-condensed table-bordered table-responsive">
            <thead>
              <th>Match %</th>
              <th>Name</th>
              <th>Full Address</th>
              <th>IPEDS</th>
              <th>OPE</th>
              <th>Action</th>
            </thead>
            <tbody>
            <% if @issue.ipeds_hd.present? %>
              <tr class="current">
                <td>Current</td>
                <td><%= @issue.ipeds_hd&.institution %></td>
                <td><%= [@issue.ipeds_hd&.addr, @issue.ipeds_hd&.state, @issue.ipeds_hd&.city, @issue.ipeds_hd&.zip].compact.join(", ") %></td>
                <td>
                  <%= link_to @issue.ipeds_hd&.cross,
                              "#{Settings.college_navigator_url}/?id=#{@issue.ipeds_hd&.cross}",
                              target: :_blank
                  %>
                <td><%= @issue.ipeds_hd&.ope %></td>
                <td/>
              </tr>
            <% end %>
            <% @possible_ipeds_matches.each do |iped| %>
              <tr>
                <td><%= (iped["match_score"].to_f * 100).round(3) %>%</td>
                <td><%= iped["institution"] %></td>
                <td><%= [iped["addr"], iped["state"], iped["city"], iped["zip"]].compact.join(", ") %></td>
                <td>
                  <%= link_to iped["cross"],
                              "#{Settings.college_navigator_url}/?id=#{iped["cross"]}",
                              target: :_blank
                  %>
                </td>
                <td><%= iped["ope"] %></td>
                <td>
                  <input
                    type="button"
                    class="btn dashboard-btn-success crosswalk_update"
                    value="Match"
                    cross="<%= iped["cross"] %>"
                    ope="<%=iped["ope"] %>"
                    />
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        <% else %>
          <p>No matches found.</p>
        <% end %>
      </div>
    </div>
    <div class="row row-space-12">
      <div class="col-xs-12">
        <h2>Crosswalk</h2>
      </div>
    </div>
    <div class="row row-space-12">
      <div class="col-xs-12">
        <%= form_with(url: crosswalk_issues_resolve_partial_path, id: 'resolve-partial-form') do %>
          <input type="hidden" name="id" value="<%= @issue.id %>" />
          <table class="table table-hover table-condensed table-bordered table-responsive">
            <thead>
              <th>Status</th>
              <th>Name</th>
              <th>Facility Code</th>
              <th>City</th>
              <th>State</th>
              <th><%= label_tag('cross', 'IPEDS') %></th>
              <th><%= label_tag('ope', 'OPE') %></th>
              <th><%= label_tag('notes', 'Notes') %></th>
              <th><%= label_tag('action', 'Action') %></th>
            </thead>
            <tbody>
              <% if @issue.crosswalk.present? %>
                <tr class="current">
                  <td>Current</td>
                  <td>
                    <%= @issue.crosswalk&.institution %>
                  </td>
                  <td>
                    <%= @issue.crosswalk&.facility_code %>
                  </td>
                  <td>
                    <%= @issue.crosswalk&.city %>
                  </td>
                  <td>
                    <%= @issue.crosswalk&.state %>
                  </td>
                  <td>
                    <%= @issue.crosswalk&.cross %>
                  </td>
                  <td>
                    <%= @issue.crosswalk&.ope %>
                  </td>
                  <td>
                    <%= @issue.crosswalk&.notes %>
                  </td>
                  <td></td>
                </tr>
              <% end %>
              <tr>
                <td>Update</td>
                <td>
                  <%= @issue.weam.institution %>
                </td>
                <td>
                  <%= @issue.weam.facility_code %>
                </td>
                <td>
                  <%= @issue.weam.city %>
                </td>
                <td>
                  <%= @issue.weam.state %>
                </td>
                <td>
                  <%= text_field_tag(:cross, @issue.crosswalk&.cross) %>
                </td>
                <td>
                  <%= text_field_tag(:ope, @issue.crosswalk&.ope) %>
                </td>
                <td>
                  <%= text_field_tag(:notes, @issue.crosswalk&.notes) %>
                </td>
                <td>
                  <input type="button" id="clear_ipeds_ope" class="btn dashboard-btn-success" value="Clear IPEDS/OPE" />
                </td>
              </tr>
            </tbody>
          </table>
          <div>
            <%= check_box_tag "ignore" %>
            <label for="ignore">Mark crosswalk issue as resolved</label>
          </div>
          <%= link_to 'Cancel', crosswalk_issues_partials_path, class: "btn dashboard-btn-danger" %>
          <%= submit_tag("Save", class: 'btn dashboard-btn-success') %>
        <% end %>
      </div>
    </div>
  </div>
</div>