config/routes.rb
Rails.application.routes.draw do
  devise_for :user

  match '/v0/*path', to: 'api#cors_preflight', via: [:options]
  match '/v1/*path', to: 'api#cors_preflight', via: [:options]
  get 'status' => 'status#status'

  get 'auth/login', to: 'auth#new', as: 'saml_login'
  post 'saml/auth/callback', to: 'auth#callback', as: 'saml_callback'
  get 'saml/metadata', to: 'auth#metadata'

  root 'application#home'

  # For active? helper
  get '/dashboards' => 'dashboards#index'
  post '/dashboards/build' => 'dashboards#build', as: :dashboard_build
  get '/dashboards/export/:csv_type' => 'dashboards#export', as: :dashboard_export, defaults: { format: 'csv' }
  get '/dashboards/api_fetch/:csv_type' => 'dashboards#api_fetch', as: :dashboard_api_fetch
  get '/dashboards/export/institutions/:number' => 'dashboards#export_version', as: :dashboard_export_version, defaults: { format: 'csv' }
  post '/dashboards/push' => 'dashboards#push', as: :dashboard_push

  resources :uploads, except: [:new, :destroy, :edit, :update] do
    get '(:csv_type)' => 'uploads#new', on: :new, as: ''
  end

  get '/groups', to: redirect('/uploads')
  resources :groups, except: [:new, :destroy, :edit, :update] do
    get '(:group_type)' => 'groups#new', on: :new, as: ''
  end

  get '/crosswalk_issues/partials' => 'crosswalk_issues#partials', as: :crosswalk_issues_partials
  get '/crosswalk_issues/partials/:id' => 'crosswalk_issues#show_partial', as: :crosswalk_issues_partials_show
  post '/crosswalk_issues/partials' => 'crosswalk_issues#resolve_partial', as: :crosswalk_issues_resolve_partial

  get '/crosswalk_issues/orphans' => 'crosswalk_issues#orphans', as: :crosswalk_issues_orphans

  get '/archives' => 'archives#index'
  get '/archives/export/:csv_type/:number' => 'archives#export', as: :archives_export, defaults: { format: 'csv' }
  get '/calculator_constants' => 'calculator_constants#index'
  post '/calculator_constants' => 'calculator_constants#update', as: :calculator_constants_update

  resources :storages, only: [:index, :edit, :update, :show] do
    get 'download' => 'storages#download', on: :member, defaults: { format: 'csv' }
  end

  namespace :v0, defaults: { format: 'json' } do
    get '/calculator/constants' => 'calculator_constants#index'

    resources :institutions, only: [:index, :show] do
      get :autocomplete, on: :collection
      get :children, on: :member
    end

    resources :institution_programs, only: [:index] do
      get :autocomplete, on: :collection
    end

    resources :yellow_ribbon_programs, only: :index

    resources :zipcode_rates, only: :show
  end

  namespace :v1, defaults: { format: 'json' } do
    get '/calculator/constants' => 'calculator_constants#index'

    resources :institutions, only: [:index, :show] do
      get :autocomplete, on: :collection
      get :children, on: :member
    end

    resources :institution_programs, only: [:index] do
      get :autocomplete, on: :collection
    end

    resources :yellow_ribbon_programs, only: :index

    resources :zipcode_rates, only: :show
  end
end

app/models/storage.rb
# frozen_string_literal: true

class Storage < ApplicationRecord
  attr_accessor :upload_file

  belongs_to :user, inverse_of: :storages

  validates_associated :user
  validates :user_id, presence: true

  validates :csv_type, uniqueness: true, inclusion: { in: UPLOAD_TYPES_ALL_NAMES }
  validates :data, :csv, presence: true
  validates :upload_file, presence: true, unless: :persisted?

  after_initialize :replace_data, unless: :persisted?

  def self.find_and_update(params)
    storage = Storage.find_by(id: params[:id])
    raise(ArgumentError, "Invalid Storage id: #{params[:id]}") if storage.blank?

    storage.upload_file = params[:upload_file]
    storage.user = params[:user]
    storage.comment = params[:comment] if params[:comment].present?

    storage.replace_data
    storage.save
    storage
  end

  def replace_data
    derive_dependent_columns
  end

  private

  def derive_dependent_columns
    self.csv = upload_file.try(:original_filename)
    self.data = File.read(upload_file.path, encoding: 'ISO-8859-1')
  rescue StandardError => e
    errors.add(:upload_file, "error reading the uploaded csv file: #{e.message}")
  end
end

app/controllers/storages_controller.rb
# frozen_string_literal: true

class StoragesController < ApplicationController
  def index
    @storages = Storage.all.order(:csv_type)
  end

  def show
    @storage = find_storage
  rescue ArgumentError, ActionController::UnknownFormat => e
    Rails.logger.error e.message
    redirect_to storages_path, alert: e.message
  end

  def edit
    @storage = find_storage
  rescue ArgumentError, ActionController::UnknownFormat => e
    Rails.logger.error e.message
    redirect_to storages_path, alert: e.message
  end

  def update
    @storage = Storage.find_and_update(merged_params)
    raise StandardError, @storage.errors.full_messages unless @storage.valid?

    redirect_to storage_path(params[:id])
  rescue ArgumentError, ActionController::UnknownFormat => e
    Rails.logger.error e.message
    redirect_to storages_path, alert: e.message
  rescue StandardError => e
    message = e.message.gsub(/[\[\]"]/, '')

    Rails.logger.error message
    flash[:alert] = message
    render :edit
  end

  def download
    @storage = find_storage

    respond_to do |format|
      format.csv { send_data @storage.data, type: 'text/csv', filename: @storage.csv }
    end
  rescue ArgumentError, ActionController::UnknownFormat => e
    Rails.logger.error e.message
    redirect_to storages_path, alert: e.message
  end

  private

  def merged_params
    upload_params.merge(user: current_user, id: params[:id])
  end

  def upload_params
    @upload_params ||= params.require(:storage).permit(:upload_file, :comment)
  end

  def find_storage
    storage = Storage.find_by(id: params[:id])
    raise(ArgumentError, "Invalid Storage id: #{params[:id]}") if storage.blank?

    storage
  end
end

app/views/storages/_csv_type_select.html.erb
<div class="form-group">
  <%= f.label(:csv_file_type) %>
  <%= f.select(:csv_type, options_for_select(UPLOAD_TYPES_ALL_NAMES),
    { include_blank: "Select Csv File Type" },
    { class: "form-control", required: true }) %>
</div>

app/views/storages/_csv_type_static.html.erb
<div class="form-group">
  <%= f.label(:csv_file_type) %><br />
  <%= f.text_field(:csv_type, disabled: true, name: "csv_type_display", id: "csv_type_display") %>
  <%= f.hidden_field(:csv_type) %>
</div>

app/views/storages/_form.html.erb
<div class="row">
  <div class="col-xs-offset-1 col-xs-7">
    <%= form_for(@storage, multipart: true) do |f| %>
      <% if @storage.csv_type.nil? %>
        <%= render partial: 'csv_type_select', locals: { f: f } %>
      <% else %>
        <%= render partial: 'csv_type_static', locals: { upload: @upload, f: f } %>
      <% end %>

      <div class="form-group">
        <%= f.label(:upload_file) %>
        <%= f.file_field(:upload_file, class: "form-control", required: true, accept: "text/csv") %>
      </div>

      <div class="form-group">
        <%= f.label(:comment) %><br />
        <%= f.text_field(:comment, style: 'width: 100%') %>
      </div>

      <div class="actions">
        <%= link_to "Cancel", uploads_path, class: "btn btn-default" %>
        <%= f.submit "Upload", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/storages/_introduction.html.erb
<div class="row row-space-6">
  <div class="col-xs-9">
    <p class="lead">
      This area is provided so that administrators can upload and download
      csvs in their original form, and store temporary work being done to them.
      The data in this resource is not validated, may differ from what is
      currently in the data service, and is provided only as a common upload and
      download area for administrators. Please do not rely on the data provided
      by these files, as uploads for this resource are not validated.
    </p>

    <p class="lead" style="font-weight: bold; font-size: small; font-style: italic; color: #EE0303">
      These uploads are not validated.
    </p>

    <p class="lead" style="font-weight: bold; font-size: small; font-style: italic; color: #EE0303">
      This is not a version control system. Previous changes will be overwritten
      with each new upload. If more than one person is editing the same csv
      at the same time, there is a certainty of changes being lost.
    </p>
  </div>

  <div class="col-xs-3">
    <% if %w(edit show).include?(action_name) %>
    <div class="row row-space-6">
      <div class="col-xs-12">
        <%= link_to 'View All Stored Csvs', storages_path,
            class: "btn dashboard-btn-info btn-xs", role: "button", style: 'width: 70%' %>
      </div>
    </div>
    <% end %>

    <div class="row row-space-6">
      <div class="col-xs-12">
        <%= link_to 'View Dashboard', dashboards_path,
            class: "btn dashboard-btn-info btn-xs", style: 'width: 70%' %>
      </div>
    </div>
  </div>
</div>

app/views/storages/_storage.html.erb
<tr>
  <td><%= storage.csv_type %></td>
  <td><%= storage.csv %></td>
  <td><%= storage.created_at&.to_formatted_s(:long_ordinal) %></td>
  <td><%= storage.user&.email %></td>
  <td><%= storage.comment || '-' %></td>
  <td>

    <% if storage.data.present? %>
      <%= link_to 'Download', download_storage_path(storage.id),
        class: "btn dashboard-btn-success btn-xs", role: "button" %>
    <% else %>
      <a disabled="disabled" class="btn dashboard-btn-warning btn-xs", role="button" >
        Download
      </a>
    <% end %>
    <%= link_to 'Upload', edit_storage_path(storage.id),
      class: "btn dashboard-btn-success btn-xs", role: "button" %>
  </td>
</tr>

app/views/storages/edit.html.erb
<div class="row row-space-6" style="padding-bottom: 10px">
  <div class="col-xs-12">
    <%= render partial: 'introduction' %>
  </div>
</div>

<div class="row">
  <div class="col-xs-8">
    <%= render 'form' %>
  </div>
</div>

app/views/storages/index.html.erb
<div class="row row-space-6" style="padding-bottom: 10px">
  <div class="col-xs-12">
    <%= render partial: 'introduction' %>
  </div>
</div>

<div class="row row-space-6">
  <div class="col-xs-11">
    <table class="table table-hover table-condensed table-bordered table-responsive">
      <thead>
        <th>CSV Type</th>
        <th>File Name</th>
        <th>Upload Date</th>
        <th>Uploaded By</th>
        <th>Comments</th>
        <th></th>
      </thead>
      <tbody>
        <%= render partial: 'storage', collection: @storages, as: :storage %>
      </tbody>
    </table>
  </div>
</div>

app/views/storages/show.html.erb
<div class="row row-space-6" style="padding-bottom: 10px">
  <div class="col-xs-12">
    <%= render partial: 'introduction' %>
  </div>
</div>

<div class="row row-space-6">
  <div class="col-xs-2">
    <strong>Id: </strong>
  </div>
  <div class="col-xs-3">
    <%= @storage.id %>
  </div>
</div>

<div class="row">
  <div class="col-xs-2">
    <strong>Type: </strong>
  </div>
  <div class="col-xs-3">
    <%= @storage.csv_type %>
  </div>
</div>

<div class="row">
  <div class="col-xs-2">
    <strong>Source File: </strong>
  </div>
  <div class="col-xs-3">
    <%= @storage.csv %>
  </div>
</div>

<div class="row">
  <div class="col-xs-2">
    <strong>Uploaded By: </strong>
  </div>
  <div class="col-xs-3">
    <%= @storage.user.email %>
  </div>
</div>

<div class="row">
  <div class="col-xs-2">
    <strong>Uploaded On: </strong>
  </div>
  <div class="col-xs-3">
    <%= @storage.created_at.strftime('%b %e, %Y %H:%M:%S') %>
  </div>
</div>

<div class="row" style: "padding-bottom: 20px">
  <div class="col-xs-2">
    <strong>Comments: </strong>
  </div>
  <div class="col-xs-3">
    <%= @storage.comment %>
  </div>
</div>