config/routes.rb
Rails.application.routes.draw do
  devise_for :user

  match '/v0/*path', to: 'api#cors_preflight', via: [:options]
  match '/v1/*path', to: 'api#cors_preflight', via: [:options]
  get 'status' => 'status#status'

  get 'auth/login', to: 'auth#new', as: 'saml_login'
  post 'saml/auth/callback', to: 'auth#callback', as: 'saml_callback'
  get 'saml/metadata', to: 'auth#metadata'

  root 'application#home'

  # For active? helper
  get '/dashboards' => 'dashboards#index'
  post '/dashboards/build' => 'dashboards#build', as: :dashboard_build
  get '/dashboards/export/:csv_type' => 'dashboards#export', as: :dashboard_export, defaults: { format: 'csv' }
  get '/dashboards/api_fetch/:csv_type' => 'dashboards#api_fetch', as: :dashboard_api_fetch
  get '/dashboards/export/institutions/:number' => 'dashboards#export_version', as: :dashboard_export_version, defaults: { format: 'csv' }
  post '/dashboards/push' => 'dashboards#push', as: :dashboard_push

  resources :uploads, except: [:new, :destroy, :edit, :update] do
    get '(:csv_type)' => 'uploads#new', on: :new, as: ''
  end

  get '/groups', to: redirect('/uploads')
  resources :groups, except: [:new, :destroy, :edit, :update] do
    get '(:group_type)' => 'groups#new', on: :new, as: ''
  end

  get '/crosswalk_issues/partials' => 'crosswalk_issues#partials', as: :crosswalk_issues_partials
  get '/crosswalk_issues/partials/:id' => 'crosswalk_issues#show_partial', as: :crosswalk_issues_partials_show
  post '/crosswalk_issues/partials' => 'crosswalk_issues#resolve_partial', as: :crosswalk_issues_resolve_partial

  get '/crosswalk_issues/orphans' => 'crosswalk_issues#orphans', as: :crosswalk_issues_orphans

  get '/archives' => 'archives#index'
  get '/archives/export/:csv_type/:number' => 'archives#export', as: :archives_export, defaults: { format: 'csv' }
  get '/calculator_constants' => 'calculator_constants#index'
  post '/calculator_constants' => 'calculator_constants#update', as: :calculator_constants_update

  resources :storages, only: [:index, :edit, :update, :show] do
    get 'download' => 'storages#download', on: :member, defaults: { format: 'csv' }
  end

  namespace :v0, defaults: { format: 'json' } do
    get '/calculator/constants' => 'calculator_constants#index'

    resources :institutions, only: [:index, :show] do
      get :autocomplete, on: :collection
      get :children, on: :member
    end

    resources :institution_programs, only: [:index] do
      get :autocomplete, on: :collection
    end

    resources :yellow_ribbon_programs, only: :index

    resources :zipcode_rates, only: :show
  end

  namespace :v1, defaults: { format: 'json' } do
    get '/calculator/constants' => 'calculator_constants#index'

    resources :institutions, only: [:index, :show] do
      get :autocomplete, on: :collection
      get :children, on: :member
    end

    resources :institution_programs, only: [:index] do
      get :autocomplete, on: :collection
    end

    resources :yellow_ribbon_programs, only: :index

    resources :zipcode_rates, only: :show
  end
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

class DashboardsController < ApplicationController
  def index
    @uploads = Upload.last_uploads_rows

    @production_versions = Version.production.newest.includes(:user).limit(1)
    @preview_versions = Version.preview.newest.includes(:user).limit(1)
    @latest_uploads = Upload.since_last_preview_version
  end

  def build
    results = InstitutionBuilder.run(current_user)

    @version = results[:version]
    @error_msg = results[:error_msg]

    if @error_msg.present?
      flash.alert = "Preview Data not built: #{@error_msg}"
    else
      flash.notice = "Preview Data (#{@version.number}) built successfully"
      flash.alert = results[:messages] if results[:messages]
    end

    redirect_to dashboards_path
  end

  def export
    file_type = params[:csv_type]
    if GROUP_FILE_TYPES_NAMES.include?(file_type)
      send_data Group.export_as_zip(file_type), type: 'application/zip', filename: "#{file_type}.zip"
    else
      klass = csv_model(file_type)

      respond_to do |format|
        format.csv { send_data klass.export, type: 'text/csv', filename: "#{klass.name}.csv" }
      end
    end
  rescue ArgumentError, ActionController::UnknownFormat => e
    log_error(e)
  end

  def export_version
    respond_to do |format|
      format.csv do
        send_data Institution.export_by_version(params[:number]),
                  type: 'text/csv',
                  filename: "institutions_version_#{params[:number]}.csv"
      end
    end
  rescue ArgumentError, Common::Exceptions::RecordNotFound, ActionController::UnknownFormat => e
    log_error(e)
  end

  def push
    version = Version.current_preview

    if version.blank?
      flash.alert = 'No preview version available'
    else
      version.update(production: true)

      flash.notice = 'Production data updated'

      # Build Sitemap and notify search engines in production only
      ping = request.original_url.include?(GibctSiteMapper::PRODUCTION_HOST)
      GibctSiteMapper.new(ping: ping)

      if Settings.archiver.archive
        # Archive previous versions of generated data
        Archiver.archive_previous_versions
      end
    end

    redirect_to dashboards_path
  end

  def api_fetch
    class_name = CSV_TYPES_HAS_API_TABLE_NAMES.find { |csv_type| csv_type == params[:csv_type] }

    if Upload.fetching_for?(params[:csv_type])
      flash.alert = "#{params[:csv_type]} is already being fetched by another user"
    elsif class_name.present?
      csv = "#{class_name}::API_SOURCE".safe_constantize || "#{class_name} API"
      begin
        api_upload = Upload.new(csv_type: class_name, user: current_user, csv: csv,
                                comment: "#{class_name} API Request")
        flash.notice = fetch_api_data(api_upload) if api_upload.save!
      rescue StandardError => e
        message = Common::Exceptions::ExceptionHandler.new(e, api_upload&.csv_type).serialize_error
        api_upload.update(ok: false, completed_at: Time.now.utc.to_s(:db), comment: message)

        Rails.logger.error e
        flash.alert = message
      end
    else
      flash.alert = "#{params[:csv_type]} is not configured to fetch data from an api"
    end

    redirect_to dashboards_path
  end

  private

  def log_error(error)
    Rails.logger.error error.message + error&.backtrace.to_s
    redirect_to dashboards_path, alert: "#{error.message}\n#{error.backtrace[0]}"
  end

  def csv_model(csv_type)
    model = CSV_TYPES_ALL_TABLES_CLASSES.select { |klass| klass.name == csv_type }.first
    return model if model.present?

    raise(ArgumentError, "#{csv_type} is not a valid exportable CSV type") if model.blank?
  end

  def fetch_api_data(api_upload)
    klass = api_upload.csv_type.constantize
    populated = klass&.respond_to?(:populate) ? klass.populate : false
    api_upload.update(ok: populated, completed_at: Time.now.utc.to_s(:db))

    if populated

      message = "#{klass.name}::POPULATE_SUCCESS_MESSAGE".safe_constantize
      return message if message.present?

      "#{klass.name} finished fetching data from its api"
    end
  end
end

app/helpers/dashboards_helper.rb
# frozen_string_literal: true

module DashboardsHelper
  def latest_upload_class(upload)
    return '' if upload.ok?
    return 'danger' if UPLOAD_TYPES_REQUIRED_NAMES.include?(upload.csv_type)

    'warning'
  end

  def latest_upload_title(upload)
    return '' if upload.ok?
    return 'Missing required upload' if UPLOAD_TYPES_REQUIRED_NAMES.include?(upload.csv_type)

    'Missing upload'
  end

  def can_generate_preview(preview_versions)
    'disabled' if preview_versions[0]&.generating?
  end

  def cannot_fetch_api(csv_type)
    Upload.fetching_for?(csv_type)
  end
end

app/views/dashboards/_crosswalk_issues.html.erb
<h2>Crosswalk Issues</h2>
<div id="crosswalk-issues-dashboard" class="row row-space-12 equal">
  <div class="col col-xs-12 col-md-6 col-lg-3">
    <div class="panel panel-default">
      <div class="panel-heading">Partial Matches</div>
      <div class="panel-body">
        <p>Weams records that partially match IPEDS or Crosswalk records</p>
        <div>
        <%= link_to crosswalk_issues_partials_path do %>
          <button class="btn dashboard-btn-success">
            View
            <span class="badge"><%= CrosswalkIssue.by_issue_type(CrosswalkIssue::PARTIAL_MATCH_TYPE).count %></span>
          </button>
        <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col col-xs-12 col-md-6 col-lg-3">
    <div class="panel panel-default">
      <div class="panel-heading">IPEDS Orphans</div>
      <div class="panel-body">
        <p>IPEDS records without matching Crosswalk record</p>
        <div>
        <%= link_to crosswalk_issues_orphans_path do %>
          <button class="btn dashboard-btn-success">
            View
            <span class="badge"><%= CrosswalkIssue.by_issue_type(CrosswalkIssue::IPEDS_ORPHAN_TYPE).count %></span>
          </button>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_introduction.html.erb
<div class="row row-space-6">
  <div class="col-xs-12">
    <p class="lead">
      These are the CSV files from which the database will be constructed.
      As the CSV is uploaded, a validation on every row in the CSV will ensure
      that there are no issues with the data. If successful, the uploaded data
      can be used to construct the Data.csv. Data may be uploaded in any desired
      order, and once all new CSV data has been uploaded, a preview version
      of the GI Bill Comparison Tool database may be built. If you are satisfied
      that the data is correct, you may "publish" the preview version of the
      database to production.
    </p>
  </div>
</div>

app/views/dashboards/_latest_upload.html.erb
<% if production? && UPLOAD_TYPES_NO_PROD_NAMES.include?(upload.csv_type) %>
<%else %>
  <tr id="row_<%=upload.csv_type%>"
      class="<%= latest_upload_class(upload) %>"
      title="<%= latest_upload_title(upload) %>">
    <td><%= upload.csv_type %></td>
    <td><%= upload.ok? ? 'Succeeded' : 'Failed' %></td>
    <td><%= upload.csv.blank? ? '-' : upload.csv %></td>
    <td><%= upload.created_at.blank? ? '-' : upload.created_at.to_formatted_s(:long_ordinal) %></td>
    <td><%= upload.user.blank? ? '-' : upload.user.email %></td>
    <td><%= upload.comment.blank? ? '-' : upload.comment %></td>
    <td class="text-center">
      <% if CSV_TYPES_HAS_API_TABLE_NAMES.include?(upload.csv_type) %>
        <%= link_to 'Fetch', dashboard_api_fetch_path(upload.csv_type),
                    class: "btn dashboard-btn-success btn-xs",
                    role: "button",
                    id: "api_fetch_" + upload.csv_type,
                    disabled: cannot_fetch_api(upload.csv_type) %>
      <% end %>

      <% if GROUP_FILE_TYPES_NAMES.include?(upload.csv_type) %>
        <%= link_to 'Upload', new_group_path(upload.csv_type),
                    class: "btn dashboard-btn-success btn-xs", role: "button" %>
      <% else %>
        <%= link_to 'Upload', new_upload_path(upload.csv_type),
                    class: "btn dashboard-btn-success btn-xs", role: "button" %>
      <% end %>

      <% if upload.ok? %>
        <%= link_to 'Export', dashboard_export_path(upload.csv_type),
                    class: "btn dashboard-btn-success btn-xs", role: "button" %>
      <% else %>
        <a disabled="disabled" class="btn dashboard-btn-warning btn-xs", role="button" >
          Export
        </a>
      <% end %>
    </td>
  </tr>
<%end %>

app/views/dashboards/_latest_upload_dialog.html.erb
<tr>
  <td><%= upload.csv_type %></td>
  <td><%= upload.csv.blank? ? '-' : upload.csv %></td>
  <td><%= upload.created_at.blank? ? '-' : upload.created_at.to_formatted_s(:long_ordinal) %></td>
  <td><%= upload.user.blank? ? '-' : upload.user.email %></td>
  <td><%= upload.comment.blank? ? '-' : upload.comment %></td>
</tr>

app/views/dashboards/_version.html.erb
<tr class="<%= 'success' if version.production? %>">
  <td><%= version.number %></td>
  <td><%= version.uuid %></td>
  <td><%= version.user&.email %></td>
  <td><%= version.created_at&.to_formatted_s(:long_ordinal) %></td>
  <td>
    <% if version.generating? %>
        <i class="fa fa-gear fa-spin" style="font-size:24px"></i>
        Reload page to refresh preview version status
    <% else %>
      <%= link_to 'Show GIBCT', version.gibct_link, target: "_blank", rel: "noopener noreferrer",
          class: "btn dashboard-btn-success btn-xs", role: "button" %>
      <%= link_to 'Download Export CSV', dashboard_export_version_path(version.number),
          class: "btn dashboard-btn-warning btn-xs", role: "button" %>
      <% if version.publishable? %>
        <%= link_to 'Publish to Production', dashboard_push_path, method: :post,
            data: { confirm: "Are you sure you wish to publish preview version #{version.number} to production?" },
            class: "btn dashboard-btn-danger btn-xs",
            role: "button",
            id: "version_publish" %>
      <% elsif version.preview? %>
          <a class="btn dashboard-btn-danger btn-xs" disabled role="button">Publish to Production</a>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/dashboards/index.html.erb
<div class="row row-space-6">
  <div class="col-xs-12">
    <%= render partial: 'introduction' %>
  </div>
</div>

<h2>Latest Production Version</h2>
<div class="row row-space-6">
  <div class="col-xs-12">
    <table class="table table-hover table-condensed table-bordered table-responsive">
      <thead>
        <th width=7%>Version Number</td>
        <th width=23%>Version UUID</th>
        <th width=20%>Published By</th>
        <th width=20%>Published Date</th>
        <th width=30%>Actions</th>
      </thead>
      <tbody>
        <%= render partial: 'version', collection: @production_versions, as: :version %>
      </tbody>
    </table>
  </div>
</div>

<h2>Latest Preview Version</h2>
<div id="preview_dialog" title="Generate New Preview Version">
  <div id="preview_dialog_div">
    <p class="generate_preview_question">
      <b>Are you sure you want to create a new preview version?</b>
    </p>
    <% if @latest_uploads.length > 0 %>
      <p>Below are the CSVs that have been uploaded since last preview generation</p>
      <div class="generate_preview_table">
        <table class="table table-hover table-condensed table-bordered table-responsive">
          <thead>
            <th>CSV Type</th>
            <th>File Name</th>
            <th>Upload Date</th>
            <th>Uploaded By</th>
            <th>Comments</th>
          </thead>
          <tbody>
          <%= render partial: 'latest_upload_dialog', collection: @latest_uploads, as: :upload %>
          </tbody>
        </table>
      </div>
    <% else %>
      <p>No new data files have been uploaded since the last preview generation</p>
      <br>
    <% end %>

    <div class="generate_preview_button_div">
      <%= link_to 'Generate New Preview Version', dashboard_build_path, method: :post,
                  class: "btn btn-warning",
                  role: "button",
                  id: "version_build"
      %>
    </div>
  </div>
</div>

<button id="preview_opener" class="btn dashboard-btn-warning btn-xs" <%= can_generate_preview(@preview_versions) %>>Generate New Preview Version</button>

<div class="row row-space-6" id="preview_versions">
    <div class="col-xs-12">
      <table class="table table-hover table-condensed table-bordered table-responsive">
        <thead>
          <th width=7%>Version Number</td>
          <th width=23%>Version UUID</th>
          <th width=20%>Created By</th>
          <th width=20%>Created Date</th>
          <th width=30%>Actions</th>
        </thead>
        <tbody>
          <%= render partial: 'version', collection: @preview_versions, as: :version if Version.previews_exist? %>
        </tbody>
      </table>
    </div>
</div>

<%= render partial: 'crosswalk_issues' %>

<h2>Latest Uploads
  <%= link_to 'View Upload History', uploads_path, class: "btn dashboard-btn-info btn-xs", role: "button" %>
</h2>
<div class="row row-space-6" id="latest_uploads">
  <div class="col-xs-12">
    <table class="table table-hover table-condensed table-bordered table-responsive">
      <thead>
        <th>File Type</th>
        <th>Status</th>
        <th>File Name</th>
        <th>Upload Date</th>
        <th>Uploaded By</th>
        <th>Comments</th>
        <th></th>
      </thead>
      <tbody>
        <%= render partial: 'latest_upload', collection: @uploads, as: :upload %>
      </tbody>
    </table>
  </div>
</div>

app/views/dashboards/show.html.erb
<%= render partial: 'introduction' %>