config/routes.rb
Rails.application.routes.draw do
  devise_for :user

  match '/v0/*path', to: 'api#cors_preflight', via: [:options]
  match '/v1/*path', to: 'api#cors_preflight', via: [:options]
  get 'status' => 'status#status'

  get 'auth/login', to: 'auth#new', as: 'saml_login'
  post 'saml/auth/callback', to: 'auth#callback', as: 'saml_callback'
  get 'saml/metadata', to: 'auth#metadata'

  root 'application#home'

  # For active? helper
  get '/dashboards' => 'dashboards#index'
  post '/dashboards/build' => 'dashboards#build', as: :dashboard_build
  get '/dashboards/export/:csv_type' => 'dashboards#export', as: :dashboard_export, defaults: { format: 'csv' }
  get '/dashboards/api_fetch/:csv_type' => 'dashboards#api_fetch', as: :dashboard_api_fetch
  get '/dashboards/export/institutions/:number' => 'dashboards#export_version', as: :dashboard_export_version, defaults: { format: 'csv' }
  post '/dashboards/push' => 'dashboards#push', as: :dashboard_push

  resources :uploads, except: [:new, :destroy, :edit, :update] do
    get '(:csv_type)' => 'uploads#new', on: :new, as: ''
  end

  get '/groups', to: redirect('/uploads')
  resources :groups, except: [:new, :destroy, :edit, :update] do
    get '(:group_type)' => 'groups#new', on: :new, as: ''
  end

  get '/crosswalk_issues/partials' => 'crosswalk_issues#partials', as: :crosswalk_issues_partials
  get '/crosswalk_issues/partials/:id' => 'crosswalk_issues#show_partial', as: :crosswalk_issues_partials_show
  post '/crosswalk_issues/partials' => 'crosswalk_issues#resolve_partial', as: :crosswalk_issues_resolve_partial

  get '/crosswalk_issues/orphans' => 'crosswalk_issues#orphans', as: :crosswalk_issues_orphans

  get '/archives' => 'archives#index'
  get '/archives/export/:csv_type/:number' => 'archives#export', as: :archives_export, defaults: { format: 'csv' }
  get '/calculator_constants' => 'calculator_constants#index'
  post '/calculator_constants' => 'calculator_constants#update', as: :calculator_constants_update

  resources :storages, only: [:index, :edit, :update, :show] do
    get 'download' => 'storages#download', on: :member, defaults: { format: 'csv' }
  end

  namespace :v0, defaults: { format: 'json' } do
    get '/calculator/constants' => 'calculator_constants#index'

    resources :institutions, only: [:index, :show] do
      get :autocomplete, on: :collection
      get :children, on: :member
    end

    resources :institution_programs, only: [:index] do
      get :autocomplete, on: :collection
    end

    resources :yellow_ribbon_programs, only: :index

    resources :zipcode_rates, only: :show
  end

  namespace :v1, defaults: { format: 'json' } do
    get '/calculator/constants' => 'calculator_constants#index'

    resources :institutions, only: [:index, :show] do
      get :autocomplete, on: :collection
      get :children, on: :member
    end

    resources :institution_programs, only: [:index] do
      get :autocomplete, on: :collection
    end

    resources :yellow_ribbon_programs, only: :index

    resources :zipcode_rates, only: :show
  end
end

app/views/layouts/_header.html.erb
<div class="page-header">
  <h1>GI Bill Comparison Tool <small class="dashboard-header"><%=controller.controller_name.humanize.singularize %></small></h1>
</div>

app/views/layouts/_messages.html.erb
<% if alert.present? %>
	<aside class="alert alert-danger">
		<% if alert.is_a? Hash %>
			<% alert.each_pair do |label, alerts| %>
				<%= pretty_error(alerts, label) %>
			<% end %>
		<% else %>
			<%= pretty_error(alert, notice || '') %>
		<% end %>
	</aside>
<% end %>

<% if notice.present? %>
	<aside class="alert alert-info">
		<% if notice.is_a? Hash %>
			<% notice.each_pair do |label, notices| %>
				<%= pretty_error(notices, label) %>
			<% end %>
		<% else %>
			<%= notice.html_safe %>
		<% end %>
	</aside>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
        data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'GIBCTDS', root_url, { class: "navbar-brand" } %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= li_active_class(root_path) %>"><%= link_if_not_active 'Dashboard', root_path %></li>
        <li class="<%= li_active_class(uploads_path) %>"><%= link_if_not_active 'Uploads', uploads_path %></li>
        <li class="<%= li_active_class(storages_path) %>"><%= link_if_not_active 'Shared Storage', storages_path %></li>
        <li class="<%= li_active_class(archives_path) %>"><%= link_if_not_active 'Archives', archives_path %></li>
        <li class="<%= li_active_class(calculator_constants_path) %>"><%= link_if_not_active 'Calculator Constants', calculator_constants_path  %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user -%>
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_upload_messages.html.erb
<% if flash[:success].present? %>
  <aside class="alert alert-success">
    <% if flash[:success].is_a? Hash %>
      <% flash[:success].each_pair do |label, successes| %>
        <%= pretty_error(successes, label) %>
      <% end %>
    <% else %>
      <%= pretty_error(flash[:success], notice || '') %>
    <% end %>
  </aside>
<% end %>

<% if flash[:warning].present? %>
  <aside class="alert alert-warning">
    <% if flash[:warning].is_a? Hash %>
      <% flash[:warning].each_pair do |label, dangers| %>
        <%= pretty_error(dangers, label) %>
      <% end %>
    <% else %>
      <%= flash[:warning].html_safe %>
    <% end %>
  </aside>
<% end %>

<% if flash[:danger].present? %>
  <aside class="alert alert-danger">
    <% if flash[:danger].is_a? Hash %>
      <% flash[:danger].each_pair do |label, dangers| %>
        <%= pretty_error(dangers, label) %>
      <% end %>
    <% else %>
      <%= flash[:danger].html_safe %>
    <% end %>
  </aside>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>GibctDataService</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', nonce: '**CSP_NONCE**' %>
  <%= csrf_meta_tags %>
	<%= javascript_pack_tag 'application' %>
</head>
<body>
	<%= render 'layouts/navbar' %>
	<%= render 'layouts/messages' %>
  <%= render '/layouts/header' %>

	<div class="container-fluid">
		<%= yield %>
	</div>
</body>
</html>